# 这个文档包含了本博客的设定信息，你可以编辑它来个性化自己的博客，

# ----------------------------------------------------------------------------------------
# 基本信息
# ----------------------------------------------------------------------------------------

name: Huizhuo Wang
description: A beginner in cryptography

# 博客的域名和二级域名
# url: 
# baseurl: /homepage

# 博客 logo 和 favicon
avatar: https://raw.githubusercontent.com/Huizhuo-Wang/homepage/refs/heads/master/images/logo.jpg
favicon: https://raw.githubusercontent.com/Huizhuo-Wang/homepage/refs/heads/master/images/favicon.jpg

# 菜单中的按钮
navigation:
  - name: Homepage
    url: /
  - name: Blog Posts
    url: /posts
  - name: About
    url: /about
  - name: Tags
    url: /tags

paginate: 8     # 每页的文章数
excerpt_separator: <!-- more -->    # 文章简介的区分标记

footer-links:     # 社交网络链接，出现在页脚
  weibo:
  behance:
  dribbble:
  email: huizhuo0520@163.com
  facebook:
  flickr:
  github: Huizhuo-Wang
  instagram:
  linkedin:
  pinterest:
  rss:
  stackoverflow:
  tumblr:
  twitter: HuizhuoWang
  youtube: huizhuo0520

footer-text: A beginner in cryptography # 页脚文字

# ----------------------------------------------------------------------------------------
# 评论区、流量统计
# ----------------------------------------------------------------------------------------

# disqus: huizhuo-wang #shortname # 与 gitalk 二选一

gitalk:
  clientID: Ov23liAJedKruDTHVgrF
  clientSecret: 70c72cbfc537afbe16fa199772d0b98ef75c0e9e 
  repo: huizhuo-wang.github.io
  owner: Huizhuo-Wang

# Google Analytics 
google_analytics: 9989910806

utteranc:
  repo: # Your github repo path, also see: https://utteranc.es

# ----------------------------------------------------------------------------------------
# 下面不要修改
# ----------------------------------------------------------------------------------------

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
