# 这个文档包含了本博客的设定信息，你可以编辑它来个性化自己的博客，

# 描述/签名
name: Huizhuo Wang
description: A beginner in cryptography

# 输入你的网站域名（如果你没有添加自己的域名，而是直接用GitHub pages分配的域名的话可以省略）
url: 

# 博客的二级域名
baseurl: /homepage

# 你的博客logo图片URL，建议尺寸不超过300px × 300px
avatar: https://raw.githubusercontent.com/Huizhuo-Wang/homepage/refs/heads/master/images/logo.jpg

# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://raw.githubusercontent.com/Huizhuo-Wang/homepage/refs/heads/master/images/favicon.jpg


# 菜单中的按钮
navigation:
  - name: HomePage
    url: /
  - name: Blog Posts
    url: /posts
  - name: About
    url: /about
  - name: Tags
    url: /tags

# 每页的文章数
paginate: 10

# 文章简介的区分标记
excerpt_separator: <!-- more -->

# 你的社交网络链接，它们会作为图标出现在你的网站页脚中，可选填写
footer-links: 
  weibo:  #请输入你的微博个性域名 https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<>
  dribbble: # https://dribbble.com/<>
  email: huizhuo0520@163.com
  facebook: #https://www.facebook.com/<>
  flickr: #https://www.flickr.com/<>
  github: https://github.com/Huizhuo-Wang
  instagram: #https://instagram.com/<>
  linkedin: #https://www.linkedin.com/in/<>
  pinterest: #https://www.pinterest.com/<>
  rss: #随便填点啥RSS就能用了
  stackoverflow: # http://stackoverflow.com/<>
  tumblr: # https://<username>.tumblr.com
  twitter: https://x.com/HuizhuoWang
  youtube: https://www.youtube.com/@huizhuo0520

# 站点页脚的文字
footer-text: A beginner in cryptography


# 评论，注意，请不要同时添加多种不同的评论区
disqus: huizhuo-wang #shortname

# 输入Gitalk相关设定，即可添加评论区，具体请看教程
gitalk:
  clientID: 
  clientSecret: 
  repo: 
  owner: 
  proxy:

# 输入Google Analytics web tracking code
google_analytics:

utteranc:
  repo: # Your github repo path, also see: https://utteranc.es

#
# !! 以下所有设置都不需要更改 !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

